### ISSUE TITLE
An option to not add timestamp in the `replay-file` mode

### ISSUE THREAD

**Issue by air3ijai** [intuit/go-loadgen#7]
**Describe the solution you'd like**
 We would like to be able to not add timestamp into the generated file.

**Input**
```
209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187
```

**Output**
```
2022-12-23T06:53:48.998+00:00 209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187
```

**Describe alternatives you've considered**
 We probably may use some logs parsers and ignore the first field.

**Additional context**
 We would like to test our logging system and it implies a kind of predefined log format. We can use `replay-file` mode but in the current behavior a timestamp will be added to every generated line. We would like to be able to change this behavior.
 Timestamp is still useful for our case, but in a different format and location. Please see [More templating options #6](6).

**Comment by air3ijai** [comment]
Looks there is some cosmetic typos. Now we get the following in the output
```
loadgen replay-file \
  --input-file-path in.log \
  --duration 2 \
  --lines-per-second 1 \
  --disable-timestamp \
  --output stdout
```
```
t 209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187`
```
An extra symbol at the start
```
t 
```

**Comment by bhattchaitanya** [comment]
ACK. fixing it right away

**Comment by bhattchaitanya** [comment]
fixed. Kindly retest when you get a chance

**Comment by bhattchaitanya** [comment]
@air3ijai also note that we have added an additional flag for you to be able to customize the timestamp
`
      --custom-timestamp-format string        Optional custom timestamp format.The default format is 2006-01-02T15:04:05.000-07:00
      `

**Comment by air3ijai** [comment]
I just did and update
```
go install github.com/intuit/go-loadgen@latest
go: downloading github.com/intuit/go-loadgen v0.0.0-20221231063551-674e189a9504
```

Sorry, for you probably it is a very basic stuff like a go developer, but for newbies like me it is not so transparent, this is why I opened another request #8.

And now I'm trying to check if I have the latest version installed
```
loadgen --version
Error: unknown flag: --version
```

And tested again
```
2022-12-31T07:13:39.735+00:00 t 209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187
```

So, `t ` is still here...

```
rm -rf /root/go/bin/go-loadgen
go install github.com/intuit/go-loadgen@latest
```
```
2022-12-31T07:16:50.667+00:00 209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187
```

And now it works as expected. Thank you for the quick fix!

**Comment by air3ijai** [comment]
Now, I'm trying to play wit the `--custom-timestamp-format`

Google showed me the following topic - [Go: time.Format: how to understand meaning of '2006-01-02' layout?](https://stackoverflow.com/questions/42217308/go-time-format-how-to-understand-meaning-of-2006-01-02-layout)

```bash
loadgen replay-file \
  --duration 1 \
  --input-file-path in.log \
  --lines-per-second 1 \
  --output stdout \
  --custom-timestamp-format "[02/Jan/2006:15:04:05 -0700]"
```

```
[31/Dec/2022:07:32:13 +0000] 209.124.125.232 - franecki2473 [22/Dec/2022:18:56:54 +0000] "GET /value-added/repurpose/partnerships/cultivate HTTP/2.0" 403 5187
```

So, I was able to reproduce timestamp in Nginx log format - thank you for implementing that!
